urls = ["https://github.com/", "https://www.youtube.com/", 
        "https://www.google.com/", "https://www.wikipedia.org/", 
        "https://www.etsy.com/", "https://www.dictionary.com/"]

urls2= ['https://www.facebook.com/',
    'https://www.amazon.com/',
    'https://www.netflix.com/',
    'https://www.instagram.com/',
    'https://www.twitter.com/',
    'https://www.linkedin.com/',
    'https://www.reddit.com/',
    'https://www.pinterest.com/',
    'https://www.stackoverflow.com/',
    'https://www.quora.com/',
    'https://www.spotify.com/',
    'https://www.microsoft.com/',
    'https://www.apple.com/',
    'https://www.yahoo.com/',
    'https://www.twitch.tv/',
    'https://www.aliexpress.com/',
    'https://www.wikipedia.org/',
    'https://www.netflix.com/',
    'https://www.linkedin.com/',
    'https://www.reddit.com/',
    'https://www.gmail.com/',
    'https://www.wordpress.com/',
    'https://www.tumblr.com/',
    'https://www.dropbox.com/',
    'https://www.slack.com/',
    'https://www.salesforce.com/',
    'https://www.alibaba.com/',
    'https://www.nike.com/',
    'https://www.cnn.com/',
    'https://www.bbc.co.uk/',
    'https://www.nytimes.com/',
    'https://www.huffpost.com/',
    'https://www.techcrunch.com/',
    'https://www.bleacherreport.com/',
    'https://www.wikipedia.org/',
    'https://www.imdb.com/',
    'https://www.tripadvisor.com/',
    'https://www.zillow.com/',
    'https://www.zara.com/',
    'https://www.bestbuy.com/',
    'https://www.target.com/',
    'https://www.walmart.com/',
    'https://www.costco.com/',
    'https://www.macys.com/',
    'https://www.kohls.com/',
    'https://www.sephora.com/',
    'https://www.ulta.com/',
    'https://www.starbucks.com/',
    'https://www.mcdonalds.com/',
    'https://www.coca-cola.com/',
    'https://www.pepsi.com/',
    'https://www.whitehouse.gov/',
    'https://www.nasa.gov/',
    'https://www.un.org/',
    'https://www.github.io/',
    'https://www.mozilla.org/']

urls3 = []